#Better Commands Configuration
lang: "en_us"
#Supported languages are cs_cz and en_us
admin_prefix: "BCMD" #What prefix should BCMD have when logging to console
betenabled: false #Is bet command enabled?